/* Aari Transactions · plain-English task labels (generated from STAGE_CHECKLISTS
   in files.html · regenerate when checklists change). Used by the in-portal
   weekly summary so agents never see raw task ids. */
window.AariTaskLabels = {
  "new_file_received": "Confirm file received and all required documents uploaded",
  "new_contract_attached": "Verify executed contract is attached",
  "new_effective_confirmed": "Identify and confirm Effective Date from contract",
  "new_closing_confirmed": "Identify and confirm Closing Date from contract",
  "new_deadlines_calculated": "Calculate all deadlines from Effective Date",
  "wtc_contract_review": "TC reviews full contract — all parties, dates, deadlines confirmed",
  "wtc_deadlines_verified": "Verify all auto-calculated deadlines are correct",
  "wtc_contacts_complete": "Confirm all party contact information is complete",
  "wtc_opening_email": "Send opening email to all parties",
  "wtc_escrow_agent": "Confirm escrow agent name, address, phone, and email on file",
  "wtc_escrow_instructions": "Send escrow opening instructions to title company",
  "wtc_hoa_initiated": "HOA status confirmed — if yes, initiate HOA document request",
  "wtc_survey_requested": "Request existing survey from seller if available",
  "wtc_title_policy_requested": "Request existing title insurance copy from seller if available",
  "uc_emd_verify": "Verify EMD amount and due date match the contract",
  "uc_emd_followup": "Follow up with title — confirm initial EMD received",
  "uc_emd_confirmed": "EMD status set to \"Confirmed in Writing\"",
  "uc_addl_followup": "Confirm additional deposit received",
  "uc_loan_app": "Confirm buyer submitted loan application",
  "uc_lender_followup": "Follow up with lender — loan in process + appraisal will be ordered",
  "uc_hoa_docs": "Request HOA documents from management company",
  "uc_tenant_lease": "Confirm seller provided lease info — if tenant occupied",
  "uc_weekly_update": "Send weekly update email to agent — every Friday",
  "insp_scheduled": "Confirm inspection is scheduled — inspector name, date, time",
  "insp_reminder_sent": "Send inspection reminder to buyer&rsquo;s agent — 24 hours before inspection",
  "insp_deadline_watch": "Inspection period deadline — confirm everyone knows the date",
  "insp_decision_followup": "Follow up with buyer&rsquo;s agent — proceeding or canceling?",
  "insp_proceed_notice": "If proceeding — confirm written notice to seller before deadline",
  "insp_cancel_notice": "If canceling — confirm written notice to seller before deadline",
  "insp_deposit_return": "If canceling — initiate deposit return process with title company",
  "insp_permits": "Follow up on any open permit issues identified during inspection",
  "insp_lender_update": "Follow up with lender — update on loan status",
  "insp_weekly_update": "Send weekly update email to agent — every Friday",
  "rem_asis_accepted": "Confirm buyer has accepted property AS-IS in writing",
  "rem_addendum_confirmed": "Credit/concession negotiated — confirm addendum executed by ALL parties",
  "rem_permits_followup": "Open permit issues — follow up on resolution status",
  "rem_lender_progress": "Follow up with lender — loan progressing + appraisal ordered",
  "rem_title_search": "Follow up with title — confirm title search in progress",
  "rem_weekly_update": "Send weekly update email to agent — every Friday",
  "app_ordered": "Confirm appraisal ordered by lender — get it in writing",
  "app_status_followup": "Follow up with lender — appraisal completed + results received",
  "app_deadline_watch": "Loan approval deadline — Day 30 from Effective Date",
  "app_satisfactory_confirm": "At/above value — confirm with lender in writing appraisal is satisfactory",
  "app_final_approval_followup": "At/above value — follow up on final loan approval status",
  "app_low_notify": "Below value — notify BOTH agents immediately, in writing",
  "app_low_decision": "Below value — document buyer/seller decision in writing",
  "app_low_addendum": "Below value — if price reduction agreed, confirm executed addendum by ALL parties",
  "app_low_deposit_return": "Below value — if cancellation, initiate deposit return with title",
  "app_loan_approved": "Loan approval received from lender IN WRITING before Day 30",
  "app_no_approval_notice": "No approval by deadline — confirm buyer&rsquo;s written notice to seller TODAY",
  "app_title_commitment": "Follow up with title — commitment on track",
  "app_weekly_update": "Send weekly update email to agent — every Friday",
  "ctc_loan_written": "Loan approval in writing ON FILE — nothing proceeds without it",
  "ctc_title_commitment_received": "Title commitment received",
  "ctc_title_review": "Review title commitment for exceptions or issues",
  "ctc_title_exceptions_notify": "Title exceptions — notify agents and parties IMMEDIATELY, in writing",
  "ctc_title_exceptions_resolved": "Confirm ALL title exceptions resolved before closing",
  "ctc_cd_received": "Closing disclosure received from lender — confirm CFPB 3-day clock",
  "ctc_closing_confirmed": "Closing date, time, and location confirmed with ALL parties",
  "ctc_walkthrough": "Walk-through scheduled — day before or day of closing",
  "ctc_estoppels": "Estoppel letters received from all tenants",
  "ctc_fincen": "FinCEN report prepared by closing agent — entity buyer",
  "ctc_firpta": "FIRPTA certification or withholding certificate on file — foreign seller",
  "ctc_48hr_reminder": "Send 48-hour closing reminder to all parties",
  "ctc_weekly_update": "Send weekly update email to agent — every Friday",
  "cl_funds_recorded": "Confirm all closing funds collected and deed recorded — written confirmation from title",
  "cl_keys": "Confirm keys delivered to buyer",
  "cl_personal_property": "Confirm all personal property per contract on premises — seller removed all trash and personal items",
  "cl_docs_filed": "Confirm closing documents received and filed — executed deed, settlement statement, all addenda",
  "cl_congrats_agent": "Send closing congratulations email to agent",
  "cl_confirm_parties": "Send closing confirmation to all parties",
  "cl_google_review": "Request Google review from agent — send review link",
  "cl_closed_stamp": "Closed date stamped on file — automatic",
  "cl_review_24h": "24-hour post-closing review request — automatic",
  "cl_archive": "Archive file — mark as closed in system"
};
