-- ============================================================================
-- Aari Transactions · Listing intake new fields (May 2026)
-- ============================================================================
-- Extends `files` with the schema-driven listing intake structure:
--   listing_property_type      → which profile sheet to load
--   listing_critical_data      → all critical fields captured at intake (jsonb)
--   listing_standouts          → the 3 standout features (when Aari generated)
--   listing_remarks            → final MLS-safe property description
--   listing_remarks_source     → 'generated' | 'agent_provided'
--   listing_remarks_scrubbed   → array of items the auto-scrubber removed
--   listing_completion_pct     → 0-100, drives portal task progress bar
--   listing_sections_done      → which portal-task sections are complete
--
-- All `add column if not exists` so re-running is safe.
-- ============================================================================

alter table public.files
  add column if not exists listing_property_type      text,
  add column if not exists listing_critical_data      jsonb default '{}'::jsonb,
  add column if not exists listing_standouts          jsonb,
  add column if not exists listing_remarks            text,
  add column if not exists listing_remarks_source     text
    check (listing_remarks_source in ('generated','agent_provided')),
  add column if not exists listing_remarks_scrubbed   jsonb default '[]'::jsonb,
  add column if not exists listing_completion_pct     integer default 0
    check (listing_completion_pct between 0 and 100),
  add column if not exists listing_sections_done      jsonb default '[]'::jsonb;

comment on column public.files.listing_property_type is
  'Property type ID from AariListingSchema (single_family, condo_villa, multi_family, lot_land, rental_long, rental_short). Determines which MLS profile sheet drives the portal follow-up task.';

comment on column public.files.listing_critical_data is
  'JSON object containing all critical fields captured at intake. Keys match field names in listing-schema.js. Source of truth for everything the agent answered before submission.';

comment on column public.files.listing_remarks is
  'Final MLS-safe property description (max 1200 chars). Either generated by edge function from listing_standouts, or pasted by agent and run through the auto-scrubber.';

comment on column public.files.listing_remarks_source is
  '"generated" → Aari wrote it from standouts. "agent_provided" → agent pasted, then auto-scrubbed.';

comment on column public.files.listing_remarks_scrubbed is
  'Array of compliance violations the auto-scrubber removed from agent-provided remarks: [{kind:"phone", original:"(239) 555-1234"}, ...]. Used for audit trail and to show the agent what got stripped.';

comment on column public.files.listing_completion_pct is
  'Percent complete across critical_data + all portal task sections. Used by the agent portal progress bar and the TC cockpit "ready for MLS" status.';

comment on column public.files.listing_sections_done is
  'Array of section IDs the agent has finished in the portal follow-up task: ["features","construction","financial"]. Matches the sections array in listing-schema.js for the file''s property type.';

-- Index on property type so the TC cockpit can filter quickly
create index if not exists files_listing_property_type_idx
  on public.files(listing_property_type)
  where listing_property_type is not null;
