-- ============================================================
-- Import Eileen's BD contacts (195 deduped from 3 batches)
-- Generated · contacts: 195
-- Run in Supabase SQL Editor.
-- Idempotent: re-running enriches existing matches, never duplicates.
-- ============================================================

BEGIN;

-- Ensure unique constraint on (owner_id, handle) for ON CONFLICT
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'bd_contacts_owner_handle_key'
  ) THEN
    ALTER TABLE bd_contacts ADD CONSTRAINT bd_contacts_owner_handle_key UNIQUE (owner_id, handle);
  END IF;
END $$;

-- Insert all 195 contacts under Eileen's owner_id (resolved from agents.first_name = 'eileen')
WITH eileen AS (
  SELECT id FROM agents WHERE LOWER(first_name) = 'eileen' LIMIT 1
)
INSERT INTO bd_contacts (owner_id, name, handle, source, stage, notes, dm_sent_at, last_touch_at)
SELECT e.id, v.name, v.handle, v.source, v.stage, v.notes, v.dm_sent_at, v.dm_sent_at
FROM eileen e
CROSS JOIN (VALUES
  ('Adrian Aguiar', '@builderbyadrian', 'IG search', 'Contacted', 'Brokerage: Starlink Realty · Email: builderbyadrian@gmail.com', NULL),
  ('Adriana Alonso', '@adrii.realtor', 'IG search', 'Contacted', 'Brokerage: Mamba Realty · Follow up in 2 days', NULL),
  ('Aileen Andino', '@realestatebyaileen', 'IG search', 'Contacted', NULL, NULL),
  ('Alana LaCava-Hearn', '@alana_sellssunshine', 'IG search', 'Hand Raise', 'Brokerage: Miloff Aubuchon Group · Email: alana@miloffaubuchon.com', NULL),
  ('Alejandra Jimenez', '@alejandrajimenez.re', 'IG search', 'Contacted', 'Brokerage: Marzucco · Follow up in 2 days', NULL),
  ('Alejandro Munoz', '@alejandromunozreator', 'IG search', 'Contacted', 'Brokerage: EXP Realty · Email: alejandromunozre@outlook.com', NULL),
  ('Alek Petrov', '@alexpetrov_realtor', 'IG search', 'Contacted', 'Brokerage: LPT Realty · Email: alex@alexpetrovswfl.com', NULL),
  ('Alex Kirilloff', '@akirilloff19', 'IG search', 'Contacted', 'Follow up in 2 days', NULL),
  ('Alexa Cambria', '@naplesrealtoralexa', 'IG search', 'Contacted', NULL, NULL),
  ('Alexis Hansen May', '@alexismaysellsswfl', 'IG search', 'Contacted', 'Brokerage: Keller Williams · Email: alexishansen@kw.com', NULL),
  ('Ali Kochno', '@alikochno.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Alison Gesuele', '@alisongesuele.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Amanda Boyer', '@swfl_amanda', 'IG search', 'Contacted', NULL, NULL),
  ('Amanda Mckinstry', '@amanda_mckinstry_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Amanda Palmer', '@amannnduhh', 'IG search', 'Contacted', 'Brokerage: Avenue Florida · Follow up in 2 days', NULL),
  ('Amy Bohn', '@amy_bohn_realtor', 'IG search', 'Hand Raise', 'Brokerage: Sellstate Advantage Realty', NULL),
  ('Amy Huber', '@amyhuber.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Anabel Consuegra', '@anabelconsuegraa', 'IG search', 'Contacted', NULL, NULL),
  ('Andre Acosta', '@andreacosta_realtor', 'IG search', 'Contacted', 'Brokerage: Marzucco Real Estate · Email: andreacostarealtor@gmail.com', NULL),
  ('Andrea Mollica', '@andreamollica_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Angely Reinosa', '@angellyrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Anthony Churlin', '@anthonychurlinrealtor', 'IG search', 'Contacted', 'Brokerage: Remax · Email: churlinrealestate@gmail.com', NULL),
  ('Ariadna de los Arcos', '@ariadna.realestate', 'IG search', 'Contacted', 'Brokerage: Hustle Bees Realty · Follow up in 2 days', NULL),
  ('Ariana Jach', '@arianajachh', 'IG search', 'Replied', 'Stage = Replied → goes in Talking bucket', NULL),
  ('Arlet Mesa', '@realtorarlet', 'IG search', 'Contacted', 'Brokerage: Realty World · Follow up in 2 days', NULL),
  ('Arlyn Hernandez', '@arlynh_realestate', 'IG search', 'Contacted', NULL, NULL),
  ('Arys Pupo', '@aryspupo_real_estate_agent', 'IG search', 'Contacted', NULL, NULL),
  ('Ashley Pon', '@ash_swfl', 'IG search', 'Contacted', NULL, NULL),
  ('Barbra Brogdon', '@barbsellsunshine', 'IG search', 'Contacted', NULL, NULL),
  ('Barry Levinson', '@levinsonluxurygroup', 'IG search', 'Contacted', NULL, NULL),
  ('Bella North', '@bella.northrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Berry Cessna', '@berrycessna', 'IG search', 'Contacted', 'Brokerage: EXP Realty · Email: soldbyberry@gmail.com', NULL),
  ('Brandon Fajardo', '@brandon_fajadaroo', 'IG search', 'Contacted', NULL, NULL),
  ('Brayan Perez', '@its_brayanperez', 'IG search', 'Contacted', NULL, NULL),
  ('Brian Giacomello', '@briangiacomello', 'IG search', 'Contacted', NULL, NULL),
  ('Brian Walker', '@mrbrianwalker', 'IG search', 'Contacted', 'Brokerage: Plunkett Realty LLC · Follow up in 2 days', NULL),
  ('Brittany Mixon', '@brittanymixon.realtor', 'IG search', 'Contacted', 'Brokerage: Mixon Team · Email: brittany@teammixon.com', NULL),
  ('Brittany Strand', '@brittanystrandrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Brooke Harris', '@brooke.harris.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Bryant Camara', '@itmustbetanke', 'IG search', 'Contacted', 'Brokerage: Easy Mortgage LLC · Follow up in 2 days', NULL),
  ('Carlos Ordinola Pestana', '@soldbycarlosfl', 'IG search', 'Contacted', 'Brokerage: Marzucco · Follow up in 2 days', NULL),
  ('Charlene Rodriguez', '@charlenerodriguezrealtor', 'IG search', 'Contacted', 'Brokerage: Rent 1 Sale 1 Realty · Email: rent1sale1cr@gmail.com', NULL),
  ('Chelsea Defina', '@thecapecoralrealtor', 'IG search', 'Hand Raise', 'Brokerage: Domain Realty · Email: chelseadefinarealty@gmail.com', NULL),
  ('Chelsea Robinson', '@capecoralfortmyersre', 'IG search', 'Contacted', NULL, NULL),
  ('Cheyla Garcia', '@cheylagarcia_realtor', 'IG search', 'Contacted', 'Email: cheylagarcia20@yahoo.com', NULL),
  ('Christopher Brent Sergakis', '@family_friends_realestate', 'IG search', 'Contacted', NULL, NULL),
  ('Claudia Garcia', '@garcia_sellshomes', 'IG search', 'Contacted', 'Brokerage: Gold Pen Group · Email: claudiagarcia.realtor25@gmail.com', NULL),
  ('Crystal Negron', '@crystal_negronsellsswfl', 'IG search', 'Hand Raise', NULL, NULL),
  ('DJ Brooks', '@djbrooks_real_estate', 'IG search', 'Contacted', NULL, NULL),
  ('Dan MacKinnon', '@dan_the_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Danelis Veliz', '@danelisveliz.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Daniel Martinez', '@dannyswhomes', 'IG search', 'Contacted', NULL, NULL),
  ('Daniela Rivera', '@daniela.realtorflorida', 'IG search', 'Contacted', NULL, NULL),
  ('Danielle J Morieko', '@dj_morieko', 'IG search', 'Contacted', NULL, NULL),
  ('Danielle M. Reidy', '@daniellereidyrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Danielle Stefanacci', '@daniellestafanacci', 'IG search', 'Contacted', 'Brokerage: Corkscrew Real Estate · Email: danielleallenswfl@gmail.com', NULL),
  ('Darahi Duran', '@darahi_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Darlen Martinez', '@darmartinez_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('David Burnham', '@buyfromburnham', 'IG search', 'Contacted', NULL, NULL),
  ('Dayana Batista', '@dayanabatista.realtor', 'IG search', 'Contacted', 'Brokerage: The Olea Group · Follow up in 2 days', NULL),
  ('Diane Coto', '@dianecoto.fl', 'IG search', 'Contacted', NULL, NULL),
  ('Doug DiBlasio', '@swflorida_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Dylan Smith', '@dylansmith10', 'IG search', 'Contacted', 'Brokerage: Compass · Email: dylan.smith@compass.com', NULL),
  ('Eduardo Linares', '@elinares.realtor', 'IG search', 'Contacted', 'Brokerage: Ace Realty · Email: eduardo@acerealtyassociates.com', NULL),
  ('Edwilis Martinez', '@edswflrealtor', 'IG search', 'Contacted', 'Brokerage: Realty ONE Group MVP · Email: floridaluxproperties@gmail.com', NULL),
  ('Elizabeth Wilson', '@cape.coralrealtor', 'IG search', 'Contacted', 'Brokerage: EXP Realty · Email: elizabeth.wilson.275413@exprealty.com', NULL),
  ('Emelin Hernandez', '@emelinrealtor', 'IG search', 'Contacted', 'Brokerage: Sellstate 5 Star Realty · Follow up in 2 days', NULL),
  ('Emily Colamarino', '@emilysellstampabay', 'IG search', 'Contacted', 'Brokerage: Circuitous Realty · Email: emily@circuitousrealty.com', NULL),
  ('Fabrizio Quintana', '@fabrizio__quintana', 'IG search', 'Contacted', NULL, NULL),
  ('Florida Rise Team', '@florida_rise_team', 'IG search', 'Contacted', 'Brokerage: KW Elevate Luxury | The Rise Team · Follow up in 2 days', NULL),
  ('Gabriel Bottan', '@gabriel.bottan', 'IG search', 'Contacted', 'Brokerage: Anchor Real Estate · Follow up in 2 days', NULL),
  ('Gibby Eagle', '@gibby-eagle-swflrealtor', 'IG search', 'Contacted', 'Brokerage: Maxim Pres+Com Realty · Email: gibbyeagle@outlook.com', NULL),
  ('Gigi Ricciardi Hull', '@gigi_naples_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Gina Hutchinson', '@gina_sells_dreamhomes', 'IG search', 'Contacted', NULL, NULL),
  ('Gladisleidys Gonzalez', '@lifestyle_gladita', 'IG search', 'Contacted', 'Brokerage: OneFamilyRealty · Follow up in 2 days', NULL),
  ('Henry Albarracin', '@henryyourswflrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Indra Lemus', '@indrasellsswfl', 'IG search', 'Contacted', NULL, NULL),
  ('Ingrid Johana Mosquera', '@ingridjmrealtor', 'IG search', 'Contacted', 'Brokerage: Realtor HomeSmart · Email: ingridplhomes@gmail.com', NULL),
  ('Jackson Simison', '@jacksonsimison', 'IG search', 'Contacted', 'Brokerage: Royal Shell Real Estate · Email: jackson@mcmurrayandmembers...', NULL),
  ('Jadiel Perez', '@jadiel.therealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Jailyn Olmeda', '@jailynolmedarealtor', 'IG search', 'Contacted', 'Brokerage: The Olea Group · Email: jailynolmedarealtor@gmail.com', NULL),
  ('James K Boyer', '@jamesboyer', 'IG search', 'Contacted', 'Brokerage: Serhant · Follow up in 2 days', NULL),
  ('Jasmin Cabral', '@cabralestates', 'IG search', 'Contacted', NULL, NULL),
  ('Jason Edouard', '@jasonedouard.realtor', 'IG search', 'Contacted', 'Brokerage: Domain Realty · Email: jason@edouardrealestate.com', NULL),
  ('Javier Casillas', '@javiercasillasrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Jennifer Paulke', '@jenniferpaulke.swfl.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Jennyfer Torres', '@jensellsswfl', 'IG search', 'Contacted', 'Brokerage: Realty One Group · Email: jennyfer@jennyfertorres.com', NULL),
  ('Jeremy DeMers', '@jeremydemera_realestate', 'IG search', 'Contacted', NULL, NULL),
  ('Jess Powell', '@jessyournaplesrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Jessica Gonzalez', '@jessysellshomes', 'IG search', 'Contacted', NULL, NULL),
  ('Jessica McKelvie', '@jessicamckelvierealtor', 'IG search', 'Contacted', 'Brokerage: Starlink Realty · Email: jessicamckelvierealtor@gmail.com', NULL),
  ('Jessie Mendoza', '@jessie.doza', 'IG search', 'Hand Raise', NULL, NULL),
  ('Joan I. Bastidas', '@joaniebastidastherealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Joel Martinez', '@joelmartinez.realtor', 'IG search', 'Contacted', 'Brokerage: Mamba Realty · Follow up in 2 days', NULL),
  ('Jorge Lopez', '@jorgelopezmiami', 'IG search', 'Contacted', NULL, NULL),
  ('Jude Termidor', '@ajricet', 'IG search', 'Contacted', 'Brokerage: Palm Paradise Realty Group · Follow up in 2 days', NULL),
  ('Juliet Bain', '@julietsellsfl', 'IG search', 'Contacted', 'Brokerage: Lokation Real Estate · Email: juliet@julietbain.com', NULL),
  ('Kaia Wilkerson', '@kaiasellsfl', 'IG search', 'Contacted', 'Brokerage: John M Wood Properties · Email: kwilkerson@johnrwood...', NULL),
  ('Kaitlin Chernyshov', '@kaitlinjacksonvillerealtor', 'IG search', 'Contacted', 'Brokerage: Unite Real Estate Gallery · Email: katiechernyshov@gmail.com', NULL),
  ('Kara Pleasant', '@kara_present_swfl_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Karina Angulo', '@karinaangulo.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Kat Sanchez', '@kat_sanchez_realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Kate Hatton', '@tampabaykate', 'IG search', 'Contacted', 'Brokerage: Keller Williams Realty · Email: katehatton@kw.com', NULL),
  ('Kate Howard', '@katehasthekey', 'IG search', 'Contacted', NULL, NULL),
  ('Kate Sauders', '@katejsauders', 'IG search', 'Contacted', 'Brokerage: Palm Paradise Realty Group · Follow up in 2 days', NULL),
  ('Kateryna Vivdenko', '@kateryna_vivdenko', 'IG search', 'Contacted', 'Brokerage: Broker One · Email: agentkateryna@miamisky.com', NULL),
  ('Katherine Jattin', '@kj_floridarealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Kayla McLead', '@yourswflrealtorkayla', 'IG search', 'Contacted', 'Brokerage: Coldwell Banker Realty · Email: kayla.mclead@cbrealty.com', NULL),
  ('Kayla Mcdonald', '@kaylasgotthekeys', 'IG search', 'Contacted', NULL, NULL),
  ('Kimberley Menkhorst', '@lavishlivingnaplesfl', 'IG search', 'Contacted', 'Brokerage: Premiere Plus Realty Co. · Follow up in 2 days', NULL),
  ('Klarissa Grumbo', '@klarissasellsitall_', 'IG search', 'Contacted', NULL, NULL),
  ('Kleydi Nodal', '@kleydi_realestate', 'IG search', 'Contacted', 'Brokerage: Mamba Realty · Email: kleydi@nodalproperties.com', NULL),
  ('Kristia Ghafari', '@kristia.sells.florida', 'IG search', 'Contacted', NULL, NULL),
  ('Laura Rojas', '@realtordeflorida', 'IG search', 'Contacted', NULL, NULL),
  ('Leidy Penton', '@leidylaura_flrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Lia Angulo', '@lia.angulosfwlrealtor', 'IG search', 'Contacted', 'Brokerage: Marzucco Real Estate · Email: infoservicesliaangulo@gmail.com', NULL),
  ('Liane Consuegra', '@lianesells_swfl', 'IG search', 'Contacted', 'Brokerage: Mamba Realty · Email: lianesellsswfl@gmail.com', NULL),
  ('Lillyam Hernandez', '@lillyam_yourfloridarealtor', 'IG search', 'Contacted', 'Brokerage: Hustle Bees Realty · Follow up in 2 days', NULL),
  ('Lindsay Blaylock', '@movemetofl_', 'IG search', 'Contacted', 'Brokerage: Charles Rutenberg Realty · Follow up in 2 days', NULL),
  ('Lissette Sanchez', '@lissette_sanchez_realestate', 'IG search', 'Contacted', NULL, NULL),
  ('Lorraine Assis', '@assislorraine_', 'IG search', 'Contacted', NULL, NULL),
  ('Lukas Castano Escobar', '@escobarlukas_', 'IG search', 'Contacted', 'Brokerage: Escobar Brothers · Follow up in 2 days', NULL),
  ('Lupita Prada', '@reallupitaprada', 'IG search', 'Contacted', 'Brokerage: Ipt Realty · Follow up in 2 days', NULL),
  ('Macy Monge', '@macymonge', 'IG search', 'Contacted', NULL, NULL),
  ('Marcella Sousa', '@marcella_realestate', 'IG search', 'Contacted', NULL, NULL),
  ('Maria Jose Escobar', '@mariajescobar.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Maria Nieto', '@maria.nieto.realestate_', 'IG search', 'Contacted', NULL, NULL),
  ('Mariah Jones', '@movewithmariah.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Mariam Gonzalez', '@mariamgonzalezrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Mariely Kenty', '@marielykenty.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Marlene Llamas Leon', '@youragentmarlenellamasleon', 'IG search', 'Contacted', 'Brokerage: LPT Realty · Follow up in 2 days', NULL),
  ('Masiel Mejia', '@masielmejiarealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Matthew Harrington', '@mharrington.r', 'IG search', 'Contacted', NULL, NULL),
  ('Matthew Huffman', '@huff_941realestate', 'IG search', 'Contacted', NULL, NULL),
  ('Maxine Groshell Bradshaw', '@maxinegroshellrealestate', 'IG search', 'Contacted', NULL, NULL),
  ('Melissa Cheetham', '@movewithmelissac', 'IG search', 'Contacted', NULL, NULL),
  ('Melissa Luzardo', '@melyturealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Melissa Rodriguez', '@thatrealtormelissa', 'IG search', 'Contacted', 'Brokerage: EXP Realty · Email: melissar@goganteam.com', NULL),
  ('Michelle Trevino', '@michelletrevinorealtor', 'IG search', 'Hand Raise', NULL, NULL),
  ('Michelle Vega', '@michelle_renee_vega', 'IG search', 'Contacted', NULL, NULL),
  ('Mike McMurray', '@mikehmcmurray', 'IG search', 'Contacted', NULL, NULL),
  ('Miraya Lane', '@mirayalane', 'IG search', 'Contacted', 'Brokerage: Keller Williams Advantage III Realty · Follow up in 2 days', NULL),
  ('Montana Wynant', '@realtor_montana', 'IG search', 'Contacted', NULL, NULL),
  ('Narvy Parra', '@narvyparrarealestate', 'IG search', 'Contacted', NULL, NULL),
  ('Natalie Perez-Benitoa', '@nattypb', 'IG search', 'Contacted', NULL, NULL),
  ('Natasha Shaw', '@natasha.realestate', 'IG search', 'Contacted', 'Brokerage: Marzucco Luxury Real Estate · Follow up in 2 days', NULL),
  ('Neymar Carrero', '@neymar.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Nicole Dahlberg', '@swflsoldbynicole', 'IG search', 'Contacted', NULL, NULL),
  ('Omar Perez', '@omar_perez97', 'IG search', 'Contacted', NULL, NULL),
  ('Paul Medina', '@paulmedinarealtor', 'IG search', 'Contacted', 'Brokerage: Access Realty · Follow up in 2 days', NULL),
  ('Pesche Robinson', '@pesche.robinson', 'IG search', 'Contacted', 'Brokerage: Serhant · Email: pesche.robinson@serhant.com', NULL),
  ('Peyton Terris', '@peyton_terris', 'IG search', 'Contacted', NULL, NULL),
  ('Rashard "Ray" Walker', '@raysellsorlando', 'IG search', 'Contacted', NULL, NULL),
  ('Renee Storms', '@listwithrenee', 'IG search', 'Contacted', 'Brokerage: John R Wood Properties · Follow up in 2 days', NULL),
  ('Rick Haas', '@ricksellsnaples', 'IG search', 'Contacted', NULL, NULL),
  ('Robert Cardenas', '@myrealtor_robert', 'IG search', 'Contacted', NULL, NULL),
  ('Roshelle Santiago', '@roshelleflrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Roxana Gonzalez', '@_roxyrealtor', 'IG search', 'Contacted', 'Brokerage: Mamba Realty · Follow up in 2 days', NULL),
  ('Ryan Jabbour', '@jabboursellshomes', 'IG search', 'Contacted', NULL, NULL),
  ('Ryan Leben', '@ryanleben_naplesluxuryrealtor', 'IG search', 'Contacted', 'Brokerage: Realty One Group · Email: ryanleben@gmail.com', NULL),
  ('Ryan Miller', '@srqrealesteryan', 'IG search', 'Contacted', NULL, NULL),
  ('Sal Messina', '@salimessina', 'IG search', 'Contacted', NULL, NULL),
  ('Samantha Haringa', '@samantha.haringa', 'IG search', 'Replied', 'Stage = Replied → goes in Talking bucket', NULL),
  ('Sandra Aguilar', '@homessoldbysandra', 'IG search', 'Contacted', 'Brokerage: Rent 1 Sale 1 Realty · Follow up in 2 days', NULL),
  ('Sasha G. Ruisz-Lopez', '@sashasoldit', 'IG search', 'Contacted', 'Brokerage: Miromar Real Estate · Follow up in 2 days', NULL),
  ('Savannah Zarris', '@savannahzarrisrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Selena Acanda', '@selenarealtor_swfl', 'IG search', 'Contacted', 'Brokerage: Innova Realtors · Follow up in 2 days', NULL),
  ('Sheera Cook', '@sheerasellsswfl', 'IG search', 'Contacted', 'Brokerage: LPT · Follow up in 2 days', NULL),
  ('Shelby N. Solley', '@swflrealtor', 'IG search', 'Contacted', 'Brokerage: Medway Realty · Email: shelbysolley@yahoo.com', NULL),
  ('Shellie Donofrio', '@shelliesellsswfl', 'IG search', 'Contacted', NULL, NULL),
  ('Skip Riddle', '@swflrealtorskip', 'IG search', 'Contacted', 'Brokerage: Compass, The Bowers Group · Email: skip.riddle@compass.com', NULL),
  ('Spencer Robinson', '@spencer_r12', 'IG search', 'Contacted', NULL, NULL),
  ('Sten Simonsen', '@realdealssten', 'IG search', 'Contacted', 'Brokerage: Keller Williams Elevate Luxury · Email: sten@millemonge.com', NULL),
  ('Steven Torres', '@storres.realtor', 'IG search', 'Contacted', NULL, NULL),
  ('Tatum Praise', '@tatumpraise', 'IG search', 'Contacted', NULL, NULL),
  ('Taylor Rompell', '@taylorsellsswfl', 'IG search', 'Contacted', NULL, NULL),
  ('Teven Gustave', '@teventherealtor', 'IG search', 'Contacted', 'Brokerage: Passkey Realty LLC · Follow up in 2 days', NULL),
  ('Tom Liddy', '@tom_liddy-swfl_realtor', 'IG search', 'Contacted', 'Brokerage: The Keyes Company · Email: tomliddyswflrealtor@gmail.com', NULL),
  ('Tony Grech', '@tonygrechrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Veronica Mora Costa', '@veronicamora.realtor', 'IG search', 'Contacted', 'Brokerage: Lifestyle International Realty · Follow up in 2 days', NULL),
  ('Victoria Nicholas', '@realtor.victorianicholas', 'IG search', 'Contacted', 'Brokerage: Real Broker LLC · Email: vnicholas.properties@gmail.com', NULL),
  ('Vikki Salese', '@naplesv2k', 'IG search', 'Contacted', NULL, NULL),
  ('Whitney Burrows', '@whitneyswflrealtor', 'IG search', 'Contacted', 'Brokerage: Remax Nautical Realty · Email: whitneysellsswfl@gmail.com', NULL),
  ('Wilmar Sosa', '@wilmarsosarealtor', 'IG search', 'Contacted', 'Brokerage: My Realty Real Estate Group · Follow up in 2 days', NULL),
  ('Yai Galarraga', '@yairealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Yaima Perez', '@yaima_perez_realtor', 'IG search', 'Contacted', 'Brokerage: Mato Realty · Follow up in 2 days', NULL),
  ('Yaquelin Albuerne Garcia', '@yaquelin.floridarealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Yasmina Santana', '@yasminanaplesrealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Yazmin Hurtado', '@yazrealtorh', 'IG search', 'Contacted', 'Follow up in 2 days', NULL),
  ('Yerimar Aguero', '@yerirealtor', 'IG search', 'Contacted', NULL, NULL),
  ('Yessenia Garcia', '@yessygarciafloridaliving', 'IG search', 'Contacted', 'Brokerage: Astra Elite Group · Follow up in 2 days', NULL),
  ('Ythamarie Rosario', '@soldbyytha', 'IG search', 'Contacted', 'Brokerage: Keller Williams Advantage III · Follow up in 2 days', NULL),
  ('Yuley Stiven', '@yuleyrealtorcapecoral', 'IG search', 'Contacted', NULL, NULL),
  ('Yuliber Barett Delgado', '@yuliberbarettrealtor', 'IG search', 'Contacted', 'Brokerage: La Rosa Realty · Follow up in 2 days', NULL),
  ('Yusnaidy Molina', '@molina_realtor7', 'IG search', 'Contacted', 'Brokerage: Hustle Bees Realty LLC · Follow up in 2 days', NULL)
) AS v(name, handle, source, stage, notes, dm_sent_at)
ON CONFLICT (owner_id, handle) DO UPDATE SET
  name = COALESCE(EXCLUDED.name, bd_contacts.name),
  -- Stage protection: don't downgrade a higher-funnel stage to Contacted
  stage = CASE
    WHEN bd_contacts.stage IN ('Signed','Discovery Booked','Hand Raise','Added to AC','In Conversation','Replied')
      AND EXCLUDED.stage = 'Contacted' THEN bd_contacts.stage
    ELSE EXCLUDED.stage
  END,
  -- Notes: enrich with any new info (concat with existing)
  notes = CASE
    WHEN bd_contacts.notes IS NULL THEN EXCLUDED.notes
    WHEN EXCLUDED.notes IS NULL THEN bd_contacts.notes
    WHEN bd_contacts.notes = EXCLUDED.notes THEN bd_contacts.notes
    ELSE bd_contacts.notes || ' · ' || EXCLUDED.notes
  END,
  last_touch_at = GREATEST(bd_contacts.last_touch_at, EXCLUDED.dm_sent_at);

COMMIT;

-- Done · 195 unique contacts imported (enrichment applied for existing matches).
